project:
  type: website
  output-dir: docs

website:
  title: "Chick-fil-A Staten Island Mall Home Page"
  description:
    Personal home page for our store 
  site-url: "https://cfasi.github.io/cfasimain/"
  navbar:
    background: primary
    search: false
    
format:
  html:
    theme: Journal
    toc: false
    css: styles.css
    
execute: 
  cache: true