project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 2024 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://cfasi.github.io/cfasimain/"
  navbar:
    background: primary
    search: false
    
format:
  html:
    theme: Journal
    toc: false
    
execute: 
  cache: true