<div style="text-align: center;">
# Chick-fil-A Staten Island Mall 
</div>
<div style="text-align: center;">
## Leadership Development Program
</div>

Welcome to the Leadership Development Program here at Chick-fil-A Staten Island Mall. Though this program is primarily for Team Leads and Shift Leads, you must complete this program to be promoted to *any* leadership role within the store. 

To be admitted to the program, you must have at least an 85 on your most previous evaluation and had a discussion with someone on the upper-leadership team. 

<div style="text-align: center;">
**Admission to the program does not mean you will receive the role. You may be removed or put on pause at any time, depending on specific circumstances.** 
</div> 

Whether you are on the path of becoming a Team Lead or a Shift Lead, the first two stages are identical. The third stage is where they differ, as Team Leads learn how to train and Shift Leads learn how to run shifts. 

If a current Team Lead wishes to become a Shift Lead, they will *not* have to complete the program again. Instead, they only will be required to complete the third stage of the Shift Lead program, where they will refine their operational skills. 

Below gives a brief explanation of what will be learned in each stage/what you will receive: 


## Stage One (Estimated Time Spent: 8 hours)

<div style="text-align: center;">
*BOH and FOH Stage One is identical*
</div>

What you will receive: 

- **Pathways 2.0**
     - A coursework created to teach you all necessary knowledge of your respective house 
- **A handbook on Google docs** 
     - An explanation of the stage, job descriptions, and traits a leader must have. 
     - Introductory knowledge that every leader must know. 
     - *Eight* multiple-choice tests that correlate with the Pathways 2.0 Coursework. 

What must be completed before Stage 2:


- **The Pathways 2.0 Coursework** 
     - Pathways will track your completion and how long it takes you to complete each module. 
- **The Eight Tests** 
     - These tests will help us track your understanding of the knowledge. 
- **A Midterm Exam**
     - This exam will consist of the knowledge you gained from both the Pathways and the introductory knowledge section of the book. 
     - It will be 50 questions and you must receive an 85 or higher to move on.
     
## Stage Two (Estimated Time Spent: 2 hours)

### FOH (Sales & Brand Growth and Hospitality)

What you will receive: 

- Stage Two handbook 
     - 4 - 5 chapters that thoroughly explain Sales & Brand Growth and Hospitality.
     - *Four* tests that correlate with the knowledge learned in the chapters.
     - **Team Leads Only:** In person training on how to count tills, settle tills, and count the safe.


What must be completed before Stage 3:

- The Stage Two book and its four tests. 
- **Team Leads Only:** Have a strong understanding of how to count tills, settle tills, and count the safe. 


### BOH (Food Safety and Food Quality)

What you will receive: 

- Stage Two handbook 
     - 4 - 5 chapters that thoroughly explain Food Safety, Food Quality, Corporate Visits, and Safe Dailys/eRQAs. 
     - *Four* tests that correlate with the knowledge learned in the chapters.
- In-person training on the Quality Improvement Visit, Food Safety Visit, and how to complete an eRQA/Safe Daily. 
     - Food Safety Visit/Safe Daily Training: 2 hours with a current leader. 
     - Quality Improvement Visit/eRQA Training: 1.5 hours with a current leader.
- In-person practice on how to run machines effectively. 

What must be completed before Stage 3:

- The Stage Two book and its four tests. 
- Have a strong understanding of the corporate visits and how to complete an eRQA/Safe Daily. 


## Stage Three (Estimated Time Spent: Varies)

### **Team Leads:**

<div style="text-align: center;">
*BOH and FOH Stage Three is identical*
</div>


What you will receive: 

- Stage Three handbook
     - Explanation of how to train each area of the store. 
     - Chapter of how to integrate learning styles into training. 
          - 10 question test to track understanding 
     - Real Life Experiences 
          - 10 videos that vary in difficulty and depict team members completing improper actions. 
          - A test in which you have to locate these errors, explain why they are wrong, and correct them. 
      - A review for the final exam. 
- Final Cumulative Exam
      - 30 Question Exam that will pull questions from each stage of the program. 
- An in-person training to go over your role, how to train, and any questions you may have. 


What must be completed before promotion:

- The Stage 3 book and its tests
- The final exam
- The 1 hour in-person training 

### **Shift Leads:** 

#### FOH 

What you will receive: 

- A Stage 3 handbook that goes over all operational knowledge a leader must know
- In-person training on how to count tills, settle tills, and count the safe. 
- In-person training on how to run a shift. 
- In-person training on how to open and close the store. 
- An in-person training to go over your role, how to lead, and any questions you may have. 
- A final evaluation on how effective you are as a leader/what areas you need to improve in. 

What must be completed before promotion:

- Reading the Stage Three book 
- Be comfortable running a shift
- Be comfortable with opening and closing
- Pass your final evaluation 


#### BOH
- A Stage 3 handbook that goes over all operational knowledge a leader must know
- In-person training on how to impact/control waste and run machines effectively. 
- In-person training on how to run a shift/do a walk-through. 
- In-person training on how to open and close the store. 
- An in-person training to go over your role, how to lead, and any questions you may have. 
- A final evaluation on how effective you are as a leader/what areas you need to improve in. 

What must be completed before promotion:

- Reading the Stage Three book 
- Be comfortable running a shift
- Be comfortable with opening and closing
- Pass your final evaluation 
  

