
<script>
  var password = "Moomoo4087!";
  var userInput = prompt("Enter password:");
  if (userInput !== password) {
    document.body.innerHTML = "<h1>Access Denied</h1>";
  }
</script>

# Leadership Links 

## Store Calendar 
- Click [here](https://cfasi.github.io/cfasimain/calendar.html) to access the calendar.

## Write-Up Form
- Click [here](https://docs.google.com/forms/d/e/1FAIpQLSd5CovuOgV2h6ddQTI_X_T8J5HihinEypm7m9TskOCfXoOHLw/viewform?usp=sf_link) to access the write up form.

## Leadership Tracker 
- Click [here](https://docs.google.com/forms/d/e/1FAIpQLSfbL2JQBL6lBp2jWo1_r1usG-LZjaw-_Oh0RrWLVSo-X2AL7w/viewform?usp=sf_link) to access the Leadership Tracker Form. 

## FOH Links: 
- Click [here](https://docs.google.com/forms/d/e/1FAIpQLScBZ2AmAK1lKfIKEPU6uIxSxflzWxnPLhBz5WNPY-bGK2Hbkw/viewform?usp=header) to access the Gold Star Form


- Click [here](https://docs.google.com/forms/d/e/1FAIpQLSeahXpsEPY4bD6kT6KlRBQhmNoTZDAgRtPxDAJEOxO3fDlmGg/viewform?usp=header) to access the FOH Compliance Tracker

## BOH Links: 
- Click [here](https://docs.google.com/forms/d/e/1FAIpQLSeWRiR_23Z4sCJnNOoJONLYRFScmP4dgkzC-hv5oQVYwzds8g/viewform?usp=header) to access the BOH Compliance Tracker

- Click [here](https://docs.google.com/spreadsheets/d/1jgj8rw-e_1y3dBkscYev8YV38uB8CLLUBp553VoiHpg/edit?usp=sharing) for BOH Leader Walkthrough


## Evaluation Links: 
- Click [here](https://docs.google.com/spreadsheets/d/1es4_3RR5YcK0m94lybvvpprJbohNpGUbeS_7eb1znkE/edit?usp=sharing) to go to the evaluation links
     - *You will only be able to access this link if you were given access to your Google Account.*

## Training Links: 

- Click [here](https://cfasi.github.io/cfasimain/program_links.html#leader-development-program-links) to go to the Leadership Development Program Overview (**Manager Link**)

## Job Descriptions

- Click [here](https://cfasi.github.io/cfasimain/directory.html) to go to the directory
