<div style="text-align: center;">
# Shift Lead (FOH/BOH)
</div>

[Back to Directory](https://cfasi.github.io/cfasimain/directory.html)

<div style="text-align: center;">
## FOH Job Description 
</div>

<iframe src="https://docs.google.com/document/d/e/2PACX-1vREm5U4m0rP1emgVy_BK-YLTlmhTbHZ5kqodeJDK60ziayGdjVceEaejt5HZeIAR9P_a8onzIwOjNKN/pub?embedded=true" width= "800" height= "600" ></iframe>

<div style="text-align: center;">
## BOH Job Description 
</div>

<iframe src="https://docs.google.com/document/d/e/2PACX-1vTb_zNJX1h2jSgkeKjIOOBzaVljYqFz3TBiREDO2QdS6MjEt_UtCcglplgr45nngIZBHgNjAp9GbTtT/pub?embedded=true" width= "800" height= "600" ></iframe>




<div style="text-align: center;">
## Neccessary Documents/Links
</div>



- [CEM Scores](https://www.cfahome.com/go/appurl.go?app=SMGCLM)
    <details> <summary>**Click here to see description** </summary>
    This is the CEM Scores homepage. CEM stands for "Customer Experience Monitor." This is when guests receive a survey about our store and fill it our for a free sandwich. It tracks numerous metrics, such as Overall Satisfaction, Taste, Temperature, Ease of Placing Order, Ease of Receiving Order, etc. and compares our scores to Corporate. It also tracks if we have gone up or down from our previous scores, and by the percentage it did. On this dashboard, you can compare the data over time, between day parts, and even see the individual comments guests leave. 
</details>
- [Speed of Service](https://analytics.cfahome.com/dashboard/speed-of-service)\
    <details> <summary>**Click here to see description** </summary>
    </details>
- [Smart Shop](https://operationshub.cfahome.com/04087/landing)
    <details> <summary>**Click here to see description** </summary>
    </details>
