<div style="text-align: center;">
# Training Videos 
</div>


## *FOH Videos*

### Food Safety
- [Cross Contamination](https://drive.google.com/file/d/1-PfFIauWb94zm47Q9SUquOt62is3yPc6/view?usp=sharing)
- [Temperature Danger Zone](https://drive.google.com/file/d/1jodvZZ2BDFhP51uAf6m4L6q3RoyjU4mz/view?usp=sharing)
- [Wash Hands](https://drive.google.com/file/d/1s_QTS0pfsb9a0EFE6_v36TuHK5YPXswi/view?usp=sharing)

### Basic Knowledge 

- [Core4](https://drive.google.com/file/d/1BrsFxBvvO6FPItVVJmqtJnue0EvF1_by/view?usp=sharing)
- [Second Mile Service](https://drive.google.com/file/d/1e1XPya88KB5Q_vxjxXK8CMQvuWmapBGK/view?usp=sharing)
- [Heard Model](https://drive.google.com/file/d/1T8hAYilCi72-IGZztocAmERiyoJS95f5/view?usp=sharing)
- [Answering the Phone](https://drive.google.com/file/d/1oQcPT49FTjmfpw_aUfLtNeHknzLKv-3W/view?usp=sharing)
- [Proper Stocklist Format](https://drive.google.com/file/d/1T9e5onnrsZJGfXkDFPF1RKk3CPUDGFE9/view?usp=sharing)
- [Making Lemonade](https://drive.google.com/file/d/1jLVopJftZvi4EsbqboQgjP7_QUHsCk8r/view?usp=sharing)
- [Coffee Base](https://drive.google.com/file/d/17rxNGNCtooMdFYPWDD1aWLavXMGpFIKg/view?usp=sharing)
- [How to Make Kids Meal Bags](https://drive.google.com/file/d/1qsjnLEWhwGMQkUgatmObgeJvz6fgfsn1/view?usp=sharing)

### Breakfast 

- [The Breakfast Menu](https://drive.google.com/file/d/1559B-zGOt8-AZwI6X9z9puz9CkBVSwu_/view?usp=sharing)

### Front Counter 
- [How to Change a Soda Bib](https://drive.google.com/file/d/1eNNZ_phhTOkC2eh3zqP_n74tC7pGnXuB/view?usp=sharing)
- [How to Stock Ice](https://drive.google.com/file/d/1zXLeuE5J4Iisrxl7A21zUakjjsNo5sVh/view?usp=sharing)
- [Upstreaming](https://drive.google.com/file/d/1rUdMX7a8wPqO_LP4zseRjFgmJMO0G-lx/view?usp=sharing)

### Register 
- [Gluten-Free Items](https://drive.google.com/file/d/1GSKm0okDaxY8INPUebMt_Qwj9FVAu0cn/view?usp=sharing)
- [Main Menu Items](https://drive.google.com/file/d/1jHPh_aBDQk-MKQO2-TkEG9MlUKdAKOcJ/view?usp=sharing)
- [How to Engage Using Core4](https://drive.google.com/file/d/18kJ-tHlJDqF8UsHRWU5xX7wOTQnBaJVb/view?usp=sharing)
- [Side Items](https://drive.google.com/file/d/1a1iDec41cvP1wLbrFXsKemYX_YHnaVqo/view?usp=sharing)
- [Salads](https://drive.google.com/file/d/19vLIAQtsISV90OmIabljjg_tdR0movrk/view?usp=sharing)
- [How to ring in a discount](https://drive.google.com/file/d/1wt31GeRzgKljXnDOeZ2LqvgCtahitl-B/view?usp=sharing)
- [DOC](https://drive.google.com/file/d/1YE2czyFqZdhTF55zuswckCPLiiB9LYyd/view?usp=sharing)
- [How to Ring in a Gift Card](https://drive.google.com/file/d/1Q4xtd1JHCkvc0j487sv9XLLxDefwNSWB/view?usp=sharing)
- [How to Prepare Register Drinks](https://drive.google.com/file/d/1ZUtB-_cgtz1GcJlH-Y7Io--t2Lzl80CY/view?usp=sharing)

### Carry-out Bagging 
- [Calling Back Food to the Kitchen](https://drive.google.com/file/d/1uYLbLzOMNh6Ke9rZmJxKWZDvkBucL3p3/view?usp=sharing)
- [Packaging](https://drive.google.com/file/d/1pU2-i79r853u2nECiy6ccfl_Tg5dxcNi/view?usp=sharing)
- [Chutes Explanation](https://drive.google.com/file/d/1rUg8qHoe4uo8Yzj-cF4vqvAKFab98K2Y/view?usp=sharing)
- [What's in the Bagging Fridge](https://drive.google.com/file/d/19aOpv75oe-nE6vhvnr6szlxjSFPiIgov/view?usp=sharing)
- [What are the Bag Sizes](https://drive.google.com/file/d/1d2ktkY9ZE3p0U8EVbe8zFrJeRNwjIErk/view?usp=sharing)
- [How to Bag a Salad](https://drive.google.com/file/d/1F9qsmjgLLFlCezgVhTVwzfTV64jJkZqk/view?usp=sharing)
- [How to Bag a Parfait](https://drive.google.com/file/d/157gwuBtYbfObi5jL3vCyiGi11gA_1IiS/view?usp=sharing)
- [How to Run an Order](https://drive.google.com/file/d/1b-fdgm9rnaVMvNbGZ8BeovLl1mFBBWc3/view?usp=sharing)

### Mobile 

- [Why do we flat lid third party desserts?](https://drive.google.com/file/d/1I65F1YZm-iUds8YP7bHKcu4FUcb6m7RF/view?usp=sharing)
- [How to Make One Drink](https://drive.google.com/file/d/124cB_jr9uP46h7ZJuZ6GgEt_T5Z85L6H/view?usp=sharing)
- [How to give out a mobile order](https://drive.google.com/file/d/1hDIAa2gPaQ0mHxEEGqgq5AIPrClAUIl4/view?usp=sharing)
- [How to Put Sauce in a Bag](https://drive.google.com/file/d/1rDEjC1dlir1-5gds_lIqFV_zfhX5oj81/view?usp=sharing)

### Desserts
- [Mocha Cold Brew](https://drive.google.com/file/d/1mc62dof3pqZ_pGOUrgGqHuvxp89NxJCm/view?usp=sharing)
- [Strawberry Frosted Lemonade](https://drive.google.com/file/d/1RUnt9-_70b7JiezzCTFxph3i-v64MKct/view?usp=sharing)
- [Iced Coffee](https://drive.google.com/file/d/16glRzMpCCQP1hxegeTGyfGNXovNCAA2d/view?usp=sharing)
- [Strawberry Shooter](https://drive.google.com/file/d/1mEBQoFiI12PYKdpoWMrs4Q3F37b3TfLv/view?usp=sharing)
- [Refill Ice Cream Machine](https://drive.google.com/file/d/182dBZHrQndQYuxe9_9JDreEoBUTM2uuH/view?usp=sharing)
- [Ice Dream Cone & Ice Dream Cup](https://drive.google.com/file/d/1FC1225ZZDG7rmAJv3XNwWZjze1ym8XmL/view?usp=sharing)
- [Frosted Beverages](https://drive.google.com/file/d/1-6l2n7Qq4XQE_29lmGC7hB9AQHz8Nzfb/view?usp=sharing)
- [Milkshakes](https://drive.google.com/file/d/1K3HxhyZKMnzn8nzeh-p2KsEhLREjDoQK/view?usp=sharing)
- [Cleaning Spindles](https://drive.google.com/file/d/1M6jmeUNmlCDpBz-ngBayj5p08PtsSk9H/view?usp=sharing)



## *BOH Videos* 

### Food Safety
- [Cross Contamination](https://drive.google.com/file/d/1-PfFIauWb94zm47Q9SUquOt62is3yPc6/view?usp=sharing)
- [Temperature Danger Zone](https://drive.google.com/file/d/1jodvZZ2BDFhP51uAf6m4L6q3RoyjU4mz/view?usp=sharing)
- [Wash Hands](https://drive.google.com/file/d/1s_QTS0pfsb9a0EFE6_v36TuHK5YPXswi/view?usp=sharing)

### Basic Knowledge 

- [Core4](https://drive.google.com/file/d/1BrsFxBvvO6FPItVVJmqtJnue0EvF1_by/view?usp=sharing)
- [Second Mile Service](https://drive.google.com/file/d/1e1XPya88KB5Q_vxjxXK8CMQvuWmapBGK/view?usp=sharing)
- [Heard Model](https://drive.google.com/file/d/1T8hAYilCi72-IGZztocAmERiyoJS95f5/view?usp=sharing)
- [Gluten-Free Items](https://drive.google.com/file/d/1GSKm0okDaxY8INPUebMt_Qwj9FVAu0cn/view?usp=sharing)
- [Milk and Egg Wash](https://drive.google.com/file/d/1Kho28zFe6uajRN10LwHu3PqjKzxtPJP8/view?usp=sharing)
- [Prepare Mac & Cheese](https://drive.google.com/file/d/1k1f9iH17yYmAPf0Mh35ogGn2erRa5TnP/view?usp=sharing)
- [Wrapping a Cookie](https://drive.google.com/file/d/1pYdLaJHgsNP8gETWhhVJ27zLudrlAP89/view?usp=sharing)

### Breakfast 
- [CFA Biscuit](https://drive.google.com/file/d/1_kjz6CD1Y--nAfVpqPIgrDoB3TY0qQSY/view?usp=sharing)

### Primary 
- [Grilled Sandwich](https://drive.google.com/file/d/1IuP8b7MB7b3Vtj9vtFexNicbtMp-TcsO/view?usp=sharing)

### Secondary

### Machines 
- [Dropping Nuggets](https://drive.google.com/file/d/1D6EhI4W6Krbs6Q-yYGbk907vCTlqQq9s/view?usp=sharing)
- [Picking Up Machines](https://drive.google.com/file/d/1UPD3QBZvFF8LlXZCZI9uo3I0ke1r5sZS/view?usp=sharing)
- [Chicken Lock Out](https://drive.google.com/file/d/1ccX2LWcvLWE1zoprh20ejm9jpZhAZpc3/view?usp=sharing)

### Fries 
- [No Salt](https://drive.google.com/file/d/1iEgfragEk4FcqN7IBr4-KTecnMQdxKwl/view?usp=sharing)
- [Dropping Fries](https://drive.google.com/file/d/1zN2bWhsL6YO8TKU_q4iT7Hm6DEDORFbI/view?usp=sharing)

### Breading
- [Filets](https://drive.google.com/file/d/1GWMIWgzVEkUgLWkg5IrAYZLiHa6Mok0X/view?usp=sharing)
- [Strips](https://drive.google.com/file/d/1kEkI00A6XAWIoeQsl1R06Ku5VNyR--Wk/view?usp=sharing)
- [Nuggets](https://drive.google.com/file/d/1HpbhwWwGgk7q-aeNq-WOd894n9S7LsCm/view?usp=sharing)
- [Reworking and Sifting](https://drive.google.com/file/d/1mpzHUM1-a-4GbUqWz0KlWDfxWyR8xg8j/view?usp=sharing)

## Filet and Rotation 

## Prep
- [Veggie Wrap](https://drive.google.com/file/d/1ltL47QnafccGl9T_hwacXgkkOWqTvT5p/view?usp=sharing)
- [Chicken Wrap](https://drive.google.com/file/d/13bn4_FY9x2C4DxH_y4CaUKZid_mQLDg7/view?usp=sharing)
- [Cobb Salad](https://drive.google.com/file/d/10t0ovCOXXVAbLqBscfzHhsBS17JH8zmv/view?usp=sharing)
- [Market Salad](https://drive.google.com/file/d/1IR3ActmoXEUOdFYMwOi7ANswEiInG9As/view?usp=sharing)
- [Fruit Cups](https://drive.google.com/file/d/1IR3ActmoXEUOdFYMwOi7ANswEiInG9As/view?usp=sharing)



